import type { UserBadgeCard } from './user_badge_gallery';

interface OwnedProfileBadge {
    id: number;
    displayName?: string;
    themeSound?: string;
}

type AuthorizedProfileBadge = Pick<UserBadgeCard, 'id' | 'title' | 'isCurrent' | 'detailUrl'>;

export interface ProfileBadgeSound {
    id: number;
    name: string;
    themeSound: string;
}

function validId(id: unknown): id is number {
    return Number.isSafeInteger(id) && (id as number) > 0;
}

function authorizedSoundUrl(badge: AuthorizedProfileBadge, sound: unknown): sound is string {
    if (typeof sound !== 'string' || typeof badge.detailUrl !== 'string') return false;
    // Both paths are generated by the server. Keep the sound tied to the exact
    // domain and badge which the gallery authorized, even if stale input remains.
    if (!/^\/d\/[^/?#\\\s]+\/badge\/[1-9]\d*$/.test(badge.detailUrl)
        || !badge.detailUrl.endsWith(`/badge/${badge.id}`)) return false;
    if (/[\u0000-\u0020\u007f\\#]/.test(sound)) return false;
    return sound.split('?')[0] === `${badge.detailUrl}/theme-sound`;
}

/** Follow the displayed profile theme; an old username badge must not override its sound. */
export function selectProfileBadgeSound(
    ownedBadges: OwnedProfileBadge[] | null | undefined,
    badgeCards: AuthorizedProfileBadge[] | null | undefined,
    currentThemeId: unknown,
): ProfileBadgeSound | null {
    if (!Array.isArray(ownedBadges) || !Array.isArray(badgeCards)) return null;
    const validCards = badgeCards.filter((card) => card && validId(card.id));
    // The profile represents no theme with 0. An explicit but invalid/expired
    // theme stays silent instead of unexpectedly playing another badge.
    const hasThemeSelection = currentThemeId !== undefined && currentThemeId !== null && currentThemeId !== 0;
    const selected = hasThemeSelection
        ? (validId(currentThemeId) ? validCards.find((card) => card.id === currentThemeId) : undefined)
        : validCards.find((card) => card.isCurrent === true);
    if (!selected) return null;
    const owned = ownedBadges.find((badge) => badge?.id === selected.id);
    if (!owned || !authorizedSoundUrl(selected, owned.themeSound)) return null;
    return {
        id: selected.id,
        name: owned.displayName || selected.title || '徽章主题',
        themeSound: owned.themeSound,
    };
}
